
spring:
  datasource:
    url: jdbc:h2:mem:account
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true

  jpa:
    defer-datasource-initialization: true
    database-platform: H2


    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: H2Dialect # H2 방언 설정

    hibernate:
      ddl-auto: update
